### ISSUE TITLE
Fatal error: ENOENT: no such file or directory, open 'tests/behat/test_results/basictest.xml'

### ISSUE THREAD

**Issue by johnbburg** [linusnorton/grunt-parallel-behat#24]
When I run tests in a local VM, I get this error. It seems that this line (https://github.com/linusnorton/grunt-parallel-behat/blob/master/tasks/lib/BehatTask.js#L93) fails because the [feature].xml file is missing. This runs fine in other environments, so I'm a bit confused as to what should be creating the file in the first place. 

Full stack trace:

```
Started: ./tests/behat/bin/behat -c ./tests/behat/behat.yml ./tests/behat/features/MyFeatures/BasicTest.feature -f junit --out tests/behat/test_results/
Fatal error: ENOENT: no such file or directory, open 'tests/behat/test_results/basictest.xml'
Error: ENOENT: no such file or directory, open 'tests/behat/test_results/basictest.xml'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.fs.readFileSync (fs.js:397:15)
  at ParallelExec.taskFinished (/vagrant/node_modules/grunt-parallel-behat/tasks/lib/BehatTask.js:93:31)
  at emitMany (events.js:108:13)
  at ParallelExec.emit (events.js:182:7)
  at ParallelExec.taskDone (/vagrant/node_modules/grunt-parallel-behat/tasks/lib/ParallelExec.js:56:14)
  at /vagrant/node_modules/underscore/underscore.js:593:19
  at ChildProcess.exithandler (child_process.js:207:5)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:862:16)
  at Socket.<anonymous> (internal/child_process.js:338:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:490:12)
```

Any ideas are appreciated. Even if it's just pointing me to where/how these xml files should be generated.

**Comment by johnbburg** [comment]
Of course I figured it out as soon as I created an issue. I simply had to run ```composer install``` in my behat directory. Nothing to see here!

**Comment by linusnorton** [comment]
No problem, thanks for updating
